# Generated by Django 6.0.3 on 2026-05-07 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='authorizer_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='validity_days',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.shipto'),
        ),
    ]
