# Generated by Django 6.0.3 on 2026-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_remove_purchaseorder_authorizer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date_required',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
