# Generated by Django 6.0.3 on 2026-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorder_date_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_order_qr/'),
        ),
    ]
